version: "3.4"

services:
  php:
    build:
      context: ./api
      target: api_platform_php
    depends_on:
      - database
    restart: unless-stopped
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=!ChangeMe!
      - POSTGRES_USER=api-platform
    volumes:
      - db_data:/var/lib/postgresql/data:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./api/docker/db/data:/var/lib/postgresql/data:rw

  caddy:
    build:
      context: api/
      target: api_platform_caddy
    depends_on:
      - php
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT: ${MERCURE_PUBLISHER_JWT:-!ChangeMe!}
      MERCURE_SUBSCRIBER_JWT: ${MERCURE_SUBSCRIBER_JWT:-!ChangeMe!}
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
      - target: 443
        published: 443
        protocol: udp

  client:
    build:
      context: ./client
      target: api_platform_client_build
    depends_on:
      - caddy
    tty: true # https://github.com/facebook/create-react-app/issues/8688
    environment:
      TLS_KEY: /data/caddy/certificates/local/localhost/localhost.key
      TLS_CERT: /data/caddy/certificates/local/localhost/localhost.crt
      API_PLATFORM_CLIENT_GENERATOR_ENTRYPOINT: http://caddy
    volumes:
      - caddy_data:/data
    ports:
      - target: 3000
        published: 3000
        protocol: tcp

volumes:
  db_data:
  caddy_data:
  caddy_config:
